In [882]:
import faiss
import numpy as np

def store_documents(embeddings):
    
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)  # Using L2 distance for similarity
    index.add(embeddings)
    return index



def save_index_to_disk(index, file_path):
    
    faiss.write_index(index, file_path)


In [883]:
import json
import numpy as np
from langchain_openai import OpenAIEmbeddings
import faiss

#todo: change private function name
#todo: change calling function to arg = arg
#todo: _arun

class Retrieve_internal:
    embeddings_model = OpenAIEmbeddings(openai_api_key="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")
    
    def __init__(self, path) -> None:
        with open(path + "/scrapData.json","r") as file:
            self.internal_docs = json.load(file)
        self.vecStore = faiss.read_index(path + '/vecStore.faiss')
            
    
    def retrieve_internal(self, input: str, max_length: int = 1000, max_size: int = 1) -> str:
        input_embedding = self.embeddings_model.embed_documents([input])
        _, indices = self.vecStore.search(np.array(input_embedding), max_size)
        ret = ''
        append_idx = 0
        while len(ret) < max_length and append_idx < max_size:
            ret += self.internal_docs[indices[0][append_idx]] + '\n'
            append_idx += 1
        return ret

a = Retrieve_internal(path='data')
print(a.retrieve_internal("my dishwasher will not dry"))

How to Fix A Dishwasher That Won't Dry Properly: Rinse Aid Dispenser
The rinse aid or the rinse aid dispensing cap could be the reason why your dishwasher is not fully drying your dishes. Without the rinse aid, the dishes will not shed water easily and will not dry properly.
How to inspect a dishwasher rinse aid dispenser:
This inspection is very simple; you will not need to disassemble your appliance or have any tools to complete this inspection.
Your rinse aid dispenser will be found on the inside of the door, remove the cap from the dispenser.
After verifying that there is rinse aid in the chamber, inspect the cap and chamber for any signs of discoloration, warping, or any other damage.
If you find any issues with your rinse aid dispenser while performing this inspection, you will need a replacement rinse aid dispenser.




In [884]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


In [885]:
xq.shape

(10000, 64)

In [886]:
k = 4                          # we want to see 4 nearest neighbors
#D, I = index.search(xb[:5], k) # sanity check
#print(I)
#print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]


In [887]:
I[:5]

array([[ 381,  207,  210,  477],
       [ 526,  911,  142,   72],
       [ 838,  527, 1290,  425],
       [ 196,  184,  164,  359],
       [ 526,  377,  120,  425]])

In [888]:
import requests
from bs4 import BeautifulSoup
import json
from youtube_transcript_api import YouTubeTranscriptApi
from typing import Optional


class ScrapUltility:
    def __init__(self) -> None:
        pass

    @classmethod
    def get_video_title(cls, video_ID: str) -> str:
        url = 'https://noembed.com/embed?url=https://www.youtube.com/watch?v='+video_ID
        result = requests.get(url)

        toJson = json.loads(result.content)
        video_title = toJson.get('title')
        return video_title

    @classmethod
    def get_youtube_title_and_trasncript(cls, video_ID: str) -> tuple():
        transcript_result = YouTubeTranscriptApi.get_transcript(video_ID)
        transcript = ''
        for d in transcript_result:
            transcript += d['text'] + ' '
        transcript = transcript.replace('\n', ' ')
        title = cls.get_video_title(video_ID)
        transcript = "vido title: "+ title + '\n' + "Transcript:\n " + transcript
        return (title,transcript)

    @classmethod
    def get_page_video_ID(cls, soup: BeautifulSoup) -> list:
    
        labels = ['div']
        classes = ['yt-video']
        results = soup.find_all(labels,class_=classes)
        viedo_ID_set = set()
        for result in results:
            # Extract and print details from each result
            video_ID = result['data-yt-init']
            if video_ID == "d6AvOkulk_g":
                continue
            viedo_ID_set.add(video_ID)
        return list(viedo_ID_set)

    @classmethod
    def get_all_title_and_transcript(cls, video_ID_list: list) -> list:
        ret = []
        for id in video_ID_list:
            try:
                ret.append(cls.get_youtube_title_and_trasncript(id))
            except Exception as e:
                print(e)
                continue
        return ret
    @classmethod
    def search_part(cls, query: str, get_video = True, get_story = True) -> str:
        # Inspect the website to find the correct URL and parameters
        url = 'https://www.partselect.com/api/search/'
        params = {'searchterm': query}
        response = requests.get(url, params=params)
        ret = ''
        if response.status_code == 200:
            try:
                soup = BeautifulSoup(response.content, 'html.parser')
                #try to determine a page is parts or not. Parts page does not have other parts
                partsList = cls.get_compatible_parts(mode='part',soup=soup, searchPart=False)
                if len(partsList) > 0:
                    ret += "This isn't a part, might be a machine. Found following compatible parts for this machine:\n"
                    for name,part_number in partsList:
                        ret += name + ";"+ part_number + '\n'
                    ret += 'that is all\n'
                    get_video = False
                    get_story = False
                else:
                    part_number_span = soup.find('span', itemprop='productID')
                    if part_number_span:
                        ret += "\nPart number: " + part_number_span.get_text().strip()
                labels = ['div','h1']
                classes = ['pd__description','title-lg','title-main','repair-story__instruction','col-md-6 mt-3']
                results = soup.find_all(labels,class_=classes)
                printed_story = False
                printed_trouble_shooting = False
                printed_name = False
                for result in results:
                    # Extract and print details from each result
                    if not printed_name and('title-lg' in result['class'] or 'title-main' in result['class']):
                        ret += "\nName: "+ result.get_text(strip=True)
                        printed_name = True

                    elif 'pd__description' in result['class']:
                        description_title = result.find('h2', class_='title-md').get_text(strip=True)
                        description = result.find('div', itemprop='description').get_text(strip=True)
                        ret += '\n'+ description_title
                        ret += description

                    elif 'repair-story__instruction' in result['class'] and get_story:
                        if not printed_story:
                            ret += "\nRepair Story From Customer:"
                            printed_story = True
                        ret += '\n' + result.get_text(strip=True)
                    else:
                        if not printed_trouble_shooting:
                            ret += "\nTrouble Shooting:"
                            printed_trouble_shooting = True
                        ret += '\n'+result.get_text(strip=True)
                if get_video:
                    video_id_list = cls.get_page_video_ID(soup)
                    title_and_transcript_list = cls.get_all_title_and_transcript(video_ID_list=video_id_list)
                    for _, transcript in title_and_transcript_list:
                        ret += '\n' + transcript
                return ret
            except Exception as e:
                print(e)
                return "unknown error"
        else:
            print("search_part: network error")
            return "network error"
        
    @classmethod
    def get_compatible_parts(cls, mode: str = 'model', source_part_ID: str = None, query: str = None, 
                             soup: BeautifulSoup = None, searchPart = True):
        if mode == 'model' and source_part_ID and query:
            params = {"SearchTerm": query}
            url = "https://www.partselect.com/Models/" + source_part_ID + "/Parts/"
            response = requests.get(url, params)
            soup = BeautifulSoup(response.content, 'html.parser')
        elif mode == 'part' and soup:
            pass
        else:
            raise Exception("get_compatible_parts: incorrect args")
        parts_divs = soup.find_all('div', class_='mega-m__part')

        parts_list = []
        for part in parts_divs:
            part_name = part.find('a', class_='mega-m__part__name')
            part_number = part_name.find_next_sibling('div')
            if part_number:
                parts_list.append((part_name.get_text(strip=True), part_number.get_text(strip=True).split(':')[-1]))
        if len(parts_list) == 0:
            return []
        ret = []
        for part_name, part_number in parts_list:
            if searchPart:
                ret.append(cls.search_part(query=part_number, get_video=False, get_story=False))
            else:
                ret.append(("name: "+ part_name," part number: " + part_number))
        return ret


In [889]:
from typing import Optional
from langchain.tools import BaseTool

DATAPATH = "data"

class SearchPartTool(BaseTool):
    name = "get part info with part number"
    description = ("use this tool if you have a part number such as WPW10500154 or PS3406972, and want to get relevent information on that part."
                   "To use the tool you must provide exactly one argument ['part']."
                   "For example: if you want to know how to install PS3406972, use this tool with argument PS3406972")

    def _run(self, part) -> str:
        return ScrapUltility.search_part(query=part,get_video=True)
    
    def _arun(self, query: str):
        raise NotImplementedError("This tool does not support async")

class RetrieveDocTool(BaseTool):
    name = "retrive troubleshoot page"
    description = ("Use this tool if you have a question about general repair or troubleshooting. "
                   "This tool need exactly one input [question]. Example inputs: "
                   "How to fix my fridge that's constantly ranning? How to fix my dishwasher door? My fridege light is broken"
                   )
    
    doc_retriever = Retrieve_internal(path=DATAPATH)
    
    
    def _run(self, question: str) -> str:
        return self.doc_retriever.retrieve_internal(input=question, max_length=3000, max_size = 5)

class SearchPartWithoutID(BaseTool):
    name = "search part without part number"
    description = ("use this tool if you want to search some part but do not have the part number or the machine model number. "
                   "This tool should only be used as last resort because it does not perform well"
                   "Need exactly one input [query], for example: dishwasher basket")
    
    def _run(self, query) -> str:
        return ScrapUltility.search_part(query=query,get_video=True)

    def _arun(self, query: str):
        raise NotImplementedError("This tool does not support async")

class RelevantPartTool(BaseTool):
    name = "Find relevant part for machine"
    description = (
    "Use this tool when you need to find related part of a machine. "
    "To use the tool you must provide exactly two argument [machine_model, query]. "
    "The first argument must be a model number of a machine, such as WDT780SAEM1. " 
    "The second argument can be a part number such as PS3406971, or a description, such as dishrack wheel. "
    "For exmaple: " 
    "question: I want a drawer track for FPHD2491KF0. Then call tool with machine_model: FPHD2491KF0, query: drawer track. "
    "question: is PS429725 compatible with my FGHS2631PF4A. Then call tool with machine_model: FPHD2491KF0, query: PS429725. "
    "If the result says it is compatible but under a different name, it is still compatible."
    )

    def _run(self, machine_model: Optional[str], query: Optional[str]):
        result =  ScrapUltility.get_compatible_parts(mode='model',source_part_ID=machine_model, query=query)
        if not result:
            return "did not found compatible parts"
        else:
            ret = ''
            for r in result:
                ret += r + '\n'
            return ret



tools = [RelevantPartTool(), SearchPartTool(), RetrieveDocTool()]
#print(RelevantPartTool()._run('WDT780SAEM1','PS3406971'))
#print(SearchPartTool()._run('PS3406971')) WDT780SAEM1
print(SearchPartTool()._run('WDT780SAEM1'))

This isn't a part, might be a machine. Found following compatible parts for this machine:
name: Lower Dishrack Wheel; part number: PS3406971
name: Upper Rack Adjuster Kit - White Wheels, Left and Right Sides; part number: PS10065979
name: Rack Track Stop; part number: PS11746591
name: Door Balance Link Kit; part number: PS972325
name: Mounting Bracket; part number: PS11745496
name: Dishwasher Positioner; part number: PS11750093
name: Dishwasher Drain Pump; part number: PS11753379
name: Dishwasher Dishrack Adjuster; part number: PS11750092
name: Dishwasher Door Seal; part number: PS12348515
name: Retainer Clip - Black; part number: PS11755736
name: Hose Clamp; part number: PS11743008
name: Dishwasher Filter; part number: PS11759673
that is all

Name: WDT780SAEM1  Whirlpool Dishwasher - Overview
Trouble Shooting:
Ask a Question
Your Question Has Been Submitted!
Pulled dishwasher from under counter, attached link to spring, hooked spring back into frame/chassis, threaded link through pull

In [890]:
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent


OPENAI_API_KEY = "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"
llm = ChatOpenAI(
    openai_api_key=OPENAI_API_KEY,
    temperature=0,
    model_name='gpt-3.5-turbo-0125'
)

conversational_memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=5,
    return_messages=True
)

agent = initialize_agent(
    agent='structured-chat-zero-shot-react-description',
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=2,
    early_stopping_method='generate',
    memory=conversational_memory
)


In [891]:
class fakeTool(BaseTool):
    name = "tool"
    description = "desc"
    def _run(input:str):
        return input
#tool = [fakeTool()]

new_prompt = agent.agent.create_prompt(
    prefix = "You are a helpful agent from part selling website PartSelect. Answer question using the Though, Action, Observation format below until you have a final answer. "
    "Answer question only use information you gathered. You can use multiple tools if needed. "
    "Customer will ask you about troubleshooting dishwasher and fridge, and find replacement parts for them. " 
    "Parts has part number. Number from PartSelect always start with ps, such as PS3406971, they also have manufacture number such as W10195416. "
    "You have access to the following tools: ",
    suffix = ("Begin! Reminder to always use the exact characters `Final Answer` when responding. Always use the exact name of the argument when using tool. "
            "Important: If you don't know how to find the answer from observation, then give final answer: Sorry I can't be of help, please visit our website www.partselect.com. Do not repeat the same action with same tool and same input argument. "
            "Important: You can only answer questions related to refridgriator or dishwasher. Including questions on relpacement part and repair"
            ),
    tools = tools
)

#print(new_prompt.messages[0].prompt.template)
agent.agent.llm_chain.prompt = new_prompt
print(new_prompt.messages[0].prompt.template)

You are a helpful agent from part selling website PartSelect. Answer question using the Though, Action, Observation format below until you have a final answer. Answer question only use information you gathered. You can use multiple tools if needed. Customer will ask you about troubleshooting dishwasher and fridge, and find replacement parts for them. Parts has part number. Number from PartSelect always start with ps, such as PS3406971, they also have manufacture number such as W10195416. You have access to the following tools: 

Find relevant part for machine: Use this tool when you need to find related part of a machine. To use the tool you must provide exactly two argument [machine_model, query]. The first argument must be a model number of a machine, such as WDT780SAEM1. The second argument can be a part number such as PS3406971, or a description, such as dishrack wheel. For exmaple: question: I want a drawer track for FPHD2491KF0. Then call tool with machine_model: FPHD2491KF0, que

In [824]:
output = agent("How to change fridge door light?")
#output = agent("The ice maker on my Whirlpool fridge is not working. Howcan I fix it?")
print(output['output'])



> Entering new AgentExecutor chain...
Thought: The customer is asking about how to change the fridge door light, which is a repair question.
Action:
```
{
  "action": "retrive troubleshoot page",
  "action_input": {"question": "How to change fridge door light?"}
}
```
Observation: How to replace a door switch:
Before you begin to replace your door switch, make sure you disconnect the appliance's power supply. The easiest way to do this is to unplug the unit from the wall. Alternatively, you could trip the appropriate switch in the circuit breaker panel, or you could remove the appropriate fuse from your home's fuse box.

Consult with an appliance repair technician if you do not feel you have the skill or the ability to successfully complete this repair.

Locate your switch. It is activated when the door closes on it, so it will be visible with the door open. It will be located somewhere along the internal frame of the refrigerator. Once you have located the door switch, remove it. Th

In [756]:
#output = agent("which PS3406971, PS11753379 is compatible with WDT780SAEM1?")
output = agent("wheel is compatible with WDT780SAEM1?")
print(output['output'])



> Entering new AgentExecutor chain...
Thought: The user is inquiring about the compatibility of a wheel with the dishwasher model WDT780SAEM1.

Action:
```
{
  "action": "Find relevant part for machine",
  "action_input": {
    "machine_model": "WDT780SAEM1",
    "query": "wheel"
  }
}
```
Observation: 
Part number: PS11749913
Name: Dishwasher Transport Wheel WPW10190778
Dishwasher Transport Wheel SpecificationsThis transport wheel is for dishwashers and attaches to the base of the dishwasher and allows you to roll the dishwasher into the cabinet during installation.
Trouble Shooting:
This part works with the following products:Dishwasher.
This part works with the following products:Whirlpool, KitchenAid, Kenmore, Maytag.
Part# WPW10190778 replaces these:AP6016621,  W10190778
In this case the dishwasher had already been installed for a few years.  After removing it, we inspected it and saw it needed a bit of TLC.  The transport wheels on the back were missing, making it harder to mov

In [807]:
print(output['chat_history'])

[HumanMessage(content='My fridge light is broken, what to do? '), AIMessage(content="Sorry I can't be of help, please visit our website www.partselect.com."), HumanMessage(content='My fridge light is broken, what to do? '), AIMessage(content="Sorry I can't be of help, please visit our website www.partselect.com."), HumanMessage(content='My fridge light is broken, what to do? '), AIMessage(content="Sorry I can't be of help, please visit our website www.partselect.com."), HumanMessage(content='The ice maker on my Whirlpool fridge is not working. Howcan I fix it?'), AIMessage(content='Final Answer: Based on the troubleshooting guide, it seems the issue with your Whirlpool fridge ice maker not working could be related to ice buildup, water fill system problems, or issues with the ice maker control. I was unable to find a compatible ice maker assembly part for your specific Whirlpool fridge model. It is recommended to follow the troubleshooting steps provided or consult a professional for f